INSERT INTO avatars (filename, display_name, wikipedia_url, created_at, updated_at)
VALUES
  ('abigail-adams.webp', 'Abigail Adams', 'https://en.wikipedia.org/wiki/Abigail_Adams', NOW(), NOW()),
  ('abraham-joshua-heschel.webp', 'Abraham Joshua Heschel', 'https://en.wikipedia.org/wiki/Abraham_Joshua_Heschel', NOW(), NOW()),
  ('ai-weiwei.webp', 'Ai Weiwei', 'https://en.wikipedia.org/wiki/Ai_Weiwei', NOW(), NOW()),
  ('alan-turing.webp', 'Alan Turing', 'https://en.wikipedia.org/wiki/Alan_Turing', NOW(), NOW()),
  ('b-17-flying-fortress.webp', 'B-17 Flying Fortress', 'https://en.wikipedia.org/wiki/Boeing_B-17_Flying_Fortress', NOW(), NOW()),
  ('barack-obama.webp', 'Barack Obama', 'https://en.wikipedia.org/wiki/Barack_Obama', NOW(), NOW()),
  ('bobby-kennedy.webp', 'Bobby Kennedy', 'https://en.wikipedia.org/wiki/Robert_F._Kennedy', NOW(), NOW()),
  ('buffalo-soldier.webp', 'Buffalo Soldier', 'https://en.wikipedia.org/wiki/Buffalo_Soldier', NOW(), NOW()),
  ('cesar-chavez.webp', 'Cesar Chavez', 'https://en.wikipedia.org/wiki/Cesar_Chavez', NOW(), NOW()),
  ('clara-barton.webp', 'Clara Barton', 'https://en.wikipedia.org/wiki/Clara_Barton', NOW(), NOW()),
  ('claus-von-stauffenberg.webp', 'Claus von Stauffenberg', 'https://en.wikipedia.org/wiki/Claus_von_Stauffenberg', NOW(), NOW()),
  ('daniel-shays.webp', 'Daniel Shays', 'https://en.wikipedia.org/wiki/Daniel_Shays', NOW(), NOW()),
  ('dolores-huerta.webp', 'Dolores Huerta', 'https://en.wikipedia.org/wiki/Dolores_Huerta', NOW(), NOW()),
  ('eisenhower.webp', 'Dwight D. Eisenhower', 'https://en.wikipedia.org/wiki/Dwight_D._Eisenhower', NOW(), NOW()),
  ('eleanor-roosevelt.webp', 'Eleanor Roosevelt', 'https://en.wikipedia.org/wiki/Eleanor_Roosevelt', NOW(), NOW()),
  ('emma-lazarus.webp', 'Emma Lazarus', 'https://en.wikipedia.org/wiki/Emma_Lazarus', NOW(), NOW()),
  ('fanny-lou-hamer.webp', 'Fanny Lou Hamer', 'https://en.wikipedia.org/wiki/Fanny_Lou_Hamer', NOW(), NOW()),
  ('francesc-sabate-llopart.webp', 'Francesc Sabaté Llopart', 'https://en.wikipedia.org/wiki/Francesc_Sabaté_Llopart', NOW(), NOW()),
  ('franklin-delano-roosevelt.webp', 'Franklin Delano Roosevelt', 'https://en.wikipedia.org/wiki/Franklin_Delano_Roosevelt', NOW(), NOW()),
  ('franklin.webp', 'Benjamin Franklin', 'https://en.wikipedia.org/wiki/Benjamin_Franklin', NOW(), NOW()),
  ('fred-korematsu.webp', 'Fred Korematsu', 'https://en.wikipedia.org/wiki/Fred_Korematsu', NOW(), NOW()),
  ('frederick-douglass.webp', 'Frederick Douglass', 'https://en.wikipedia.org/wiki/Frederick_Douglass', NOW(), NOW()),
  ('frieda-belinfante.webp', 'Frieda Belinfante', 'https://en.wikipedia.org/wiki/Frieda_Belinfante', NOW(), NOW()),
  ('george-orwell.webp', 'George Orwell', 'https://en.wikipedia.org/wiki/George_Orwell', NOW(), NOW()),
  ('george-washington.webp', 'George Washington', 'https://en.wikipedia.org/wiki/George_Washington', NOW(), NOW()),
  ('geronimo.webp', 'Geronimo', 'https://en.wikipedia.org/wiki/Geronimo', NOW(), NOW()),
  ('grace-lee-boggs.webp', 'Grace Lee Boggs', 'https://en.wikipedia.org/wiki/Grace_Lee_Boggs', NOW(), NOW()),
  ('greta-thunberg.webp', 'Greta Thunberg', 'https://en.wikipedia.org/wiki/Greta_Thunberg', NOW(), NOW()),
  ('hamilton.webp', 'Alexander Hamilton', 'https://en.wikipedia.org/wiki/Alexander_Hamilton', NOW(), NOW()),
  ('harriet-beecher-stowe.webp', 'Harriet Beecher Stowe', 'https://en.wikipedia.org/wiki/Harriet_Beecher_Stowe', NOW(), NOW()),
  ('harriet-tubman.webp', 'Harriet Tubman', 'https://en.wikipedia.org/wiki/Harriet_Tubman', NOW(), NOW()),
  ('humayun-khan.webp', 'Humayun Khan', 'https://en.wikipedia.org/wiki/Humayun_Khan_(soldier)', NOW(), NOW()),
  ('ida-b-welles.webp', 'Ida B. Wells', 'https://en.wikipedia.org/wiki/Ida_B._Wells', NOW(), NOW()),
  ('james-baldwin.webp', 'James Baldwin', 'https://en.wikipedia.org/wiki/James_Baldwin', NOW(), NOW()),
  ('john-brown.webp', 'John Brown', 'https://en.wikipedia.org/wiki/John_Brown_(abolitionist)', NOW(), NOW()),
  ('john-f-kennedy.webp', 'John F. Kennedy', 'https://en.wikipedia.org/wiki/John_F._Kennedy', NOW(), NOW()),
  ('john-peter-zenger.webp', 'John Peter Zenger', 'https://en.wikipedia.org/wiki/John_Peter_Zenger', NOW(), NOW()),
  ('lech-walesa.webp', 'Lech Wałęsa', 'https://en.wikipedia.org/wiki/Lech_Wałęsa', NOW(), NOW()),
  ('lincoln.webp', 'Abraham Lincoln', 'https://en.wikipedia.org/wiki/Abraham_Lincoln', NOW(), NOW()),
  ('lincoln-memorial.webp', 'Lincoln Memorial', 'https://en.wikipedia.org/wiki/Lincoln_Memorial', NOW(), NOW()),
  ('linda-sarsour.webp', 'Linda Sarsour', 'https://en.wikipedia.org/wiki/Linda_Sarsour', NOW(), NOW()),
  ('malala-yousafzai.webp', 'Malala Yousafzai', 'https://en.wikipedia.org/wiki/Malala_Yousafzai', NOW(), NOW()),
  ('marsha-p-johnson.webp', 'Marsha P. Johnson', 'https://en.wikipedia.org/wiki/Marsha_P._Johnson', NOW(), NOW()),
  ('maya-angelou.webp', 'Maya Angelou', 'https://en.wikipedia.org/wiki/Maya_Angelou', NOW(), NOW()),
  ('muhammad-ali.webp', 'Muhammad Ali', 'https://en.wikipedia.org/wiki/Muhammad_Ali', NOW(), NOW()),
  ('navajo-code-talker.webp', 'Code Talker', 'https://en.wikipedia.org/wiki/Navajo_Code_Talkers', NOW(), NOW()),
  ('nelson-mandela.webp', 'Nelson Mandela', 'https://en.wikipedia.org/wiki/Nelson_Mandela', NOW(), NOW()),
  ('oskar-schindler.webp', 'Oskar Schindler', 'https://en.wikipedia.org/wiki/Oskar_Schindler', NOW(), NOW()),
  ('patrick-henry.webp', 'Patrick Henry', 'https://en.wikipedia.org/wiki/Patrick_Henry', NOW(), NOW()),
  ('patsy-mink.webp', 'Patsy Mink', 'https://en.wikipedia.org/wiki/Patsy_Mink', NOW(), NOW()),
  ('rachel-carson.webp', 'Rachel Carson', 'https://en.wikipedia.org/wiki/Rachel_Carson', NOW(), NOW()),
  ('rosa-parks.webp', 'Rosa Parks', 'https://en.wikipedia.org/wiki/Rosa_Parks', NOW(), NOW()),
  ('sacagawea.webp', 'Sacagawea', 'https://en.wikipedia.org/wiki/Sacagawea', NOW(), NOW()),
  ('sherman.webp', 'William Tecumseh Sherman', 'https://en.wikipedia.org/wiki/William_Tecumseh_Sherman', NOW(), NOW()),
  ('shirley-chisholm.webp', 'Shirley Chisholm', 'https://en.wikipedia.org/wiki/Shirley_Chisholm', NOW(), NOW()),
  ('statue-of-liberty.webp', 'Statue of Liberty', 'https://en.wikipedia.org/wiki/Statue_of_Liberty', NOW(), NOW()),
  ('tecumseh.webp', 'Tecumseh', 'https://en.wikipedia.org/wiki/Tecumseh', NOW(), NOW()),
  ('thurgood-marshall.webp', 'Thurgood Marshall', 'https://en.wikipedia.org/wiki/Thurgood_Marshall', NOW(), NOW()),
  ('tuskeegee-airman.webp', 'Tuskeegee Airman', 'https://en.wikipedia.org/wiki/Tuskegee_Airmen', NOW(), NOW()),
  ('vaclav-havel.webp', 'Václav Havel', 'https://en.wikipedia.org/wiki/Václav_Havel', NOW(), NOW()),
  ('violet-gibson.webp', 'Violet Gibson', 'https://en.wikipedia.org/wiki/Violet_Gibson', NOW(), NOW()),
  ('willem-arondeus.webp', 'Willem Arondeus', 'https://en.wikipedia.org/wiki/Willem_Arondeus', NOW(), NOW()),
  ('wilma-mankiller.webp', 'Wilma Mankiller', 'https://en.wikipedia.org/wiki/Wilma_Mankiller', NOW(), NOW()),
  ('woody-guthrie.webp', 'Woody Guthrie', 'https://en.wikipedia.org/wiki/Woody_Guthrie', NOW(), NOW())
ON CONFLICT (filename) DO UPDATE 
SET 
  display_name = EXCLUDED.display_name,
  wikipedia_url = EXCLUDED.wikipedia_url,
  updated_at = NOW();