packages:
  - apps/*
  - infra
  - packages/*
  - tooling/*

catalog:
  "@hookform/resolvers": ^3.9.0
  "@node-rs/argon2": ^2.0.2
  "@node-rs/argon2-linux-x64-gnu": ^2.0.2
  "@opennextjs/aws": ^3.1.3
  "@react-native-async-storage/async-storage": ^2.0.0
  "@react-navigation/native": ^6.0.2
  "@rn-primitives/avatar": ~1.1.0
  "@rn-primitives/portal": ~1.1.0
  "@rn-primitives/progress": ~1.1.0
  "@rn-primitives/slot": ~1.1.0
  "@rn-primitives/tooltip": ~1.1.0
  "@rn-primitives/types": ~1.1.0
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": 11.0.0-rc.477
  "@trpc/next": 11.0.0-rc.477
  "@trpc/react-query": 11.0.0-rc.477
  "@trpc/server": 11.0.0-rc.477
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  dayjs: ^1.11.13
  eslint: ^9.12.0
  expo-secure-store: ^13.0.2
  lucide-react-native: ^0.456.0
  nativewind: ~4.1.21
  next: ^14.2.23
  open-next: ^3.1.3
  prettier: ^3.3.3
  react-hook-form: ^7.53.0
  react-native-fetch-api: ^3.0.0
  react-native-reanimated: ^3.16.4
  react-native-svg: ^15.9.0
  solito: ^4.2.2
  sst: ^3
  stripe: ^17.5.0
  superjson: ^2.2.1
  tailwind-merge: ^2.5.4
  tailwindcss: ^3.4.14
  tailwindcss-animate: ^1.0.7
  typescript: ^5.6.3
  zeego: ^2.0.1
  zod: ^3.23.8
  zustand: ^5.0.0

catalogs:
  react-for-expo:
    # Only include React versions that are compatible with Expo
    # We do not include Expo itself in this catalog because
    # it is not needed in every app and package
    "@react-native/assets-registry": ~0.76.2
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
    react: 18.3.1
    react-dom: 18.3.1
    react-native: ~0.76.1
