packages:
  - apps/*
  - infra
  - packages/*
  - tooling/*

catalog:
  "@hookform/resolvers": ^3.9.0
  "@node-rs/argon2": ^2.0.2
  "@node-rs/argon2-linux-x64-gnu": ^2.0.2
  "@opennextjs/aws": ^3.1.3
  "@react-native-async-storage/async-storage": ^2.0.0
  "@react-navigation/native": ^6.0.2
  "@rn-primitives/accordion": ~1.1.0
  "@rn-primitives/alert-dialog": ~1.1.0
  "@rn-primitives/aspect-ratio": ~1.1.0
  "@rn-primitives/avatar": ~1.1.0
  "@rn-primitives/checkbox": ~1.1.0
  "@rn-primitives/collapsible": ~1.1.0
  "@rn-primitives/context-menu": ~1.1.0
  "@rn-primitives/dialog": ~1.1.0
  "@rn-primitives/dropdown-menu": ~1.1.0
  "@rn-primitives/hover-card": ~1.1.0
  "@rn-primitives/label": ~1.1.0
  "@rn-primitives/menubar": ~1.1.0
  "@rn-primitives/navigation-menu": ~1.1.0
  "@rn-primitives/popover": ~1.1.0
  "@rn-primitives/portal": ~1.1.0
  "@rn-primitives/progress": ~1.1.0
  "@rn-primitives/radio-group": ~1.1.0
  "@rn-primitives/select": ~1.1.0
  "@rn-primitives/separator": ~1.1.0
  "@rn-primitives/slot": ~1.1.0
  "@rn-primitives/switch": ~1.1.0
  "@rn-primitives/table": ~1.1.0
  "@rn-primitives/tabs": ~1.1.0
  "@rn-primitives/toggle": ~1.1.0
  "@rn-primitives/toggle-group": ~1.1.0
  "@rn-primitives/tooltip": ~1.1.0
  "@rn-primitives/types": ~1.1.0
  "@shopify/flash-list": ^1.7.1
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": 11.0.0-rc.477
  "@trpc/next": 11.0.0-rc.477
  "@trpc/react-query": 11.0.0-rc.477
  "@trpc/server": 11.0.0-rc.477
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  dayjs: ^1.11.13
  eslint: ^9.19.0
  expo-blur: ^14.0.3
  expo-clipboard: ^7.0.1
  expo-constants: ^17.0.5
  expo-dev-client: ^5.0.10
  expo-device: ^7.0.2
  expo-font: ^13.0.3
  expo-image: ^2.0.4
  expo-linking: ^7.0.5
  expo-location: ^18.0.5
  expo-navigation-bar: ^4.0.7
  expo-router: ^4.0.17
  expo-secure-store: ^14.0.1
  expo-sharing: ^13.0.1
  expo-splash-screen: ^0.29.21
  expo-status-bar: ^2.0.1
  expo-system-ui: ^4.0.7
  lucide-react-native: ^0.456.0
  nativewind: ^4.1.23
  next: ^14.2.23
  normalize-url: ^8.0.1
  open-next: ^3.1.3
  prettier: ^3.4.2
  react-hook-form: ^7.53.0
  react-native-bouncy-checkbox: ^4.1.2
  react-native-css-interop: ~0.1.22
  react-native-fetch-api: ^3.0.0
  react-native-get-random-values: ^1.11.0
  react-native-markdown-display: ^7.0.2
  react-native-otp-entry: ^1.8.2
  react-native-qrcode-svg: ^6.3.12
  react-native-reanimated: ^3.16.4
  react-native-safe-area-context: ^5.1.0
  react-native-screens: ^4.4.0
  react-native-svg: ^15.8.0
  react-native-url-polyfill: ^2.0.0
  solito: ^4.2.2
  sst: ^3
  stripe: ^17.5.0
  superjson: ^2.2.1
  tailwind-merge: ^2.5.4
  tailwindcss: ^3.4.14
  tailwindcss-animate: ^1.0.7
  typescript: ^5.7.3
  zeego: ^2.0.1
  zod: ^3.23.8
  zustand: ^5.0.0

catalogs:
  react-for-expo:
    # Only include React versions that are compatible with Expo
    # We do not include Expo itself in this catalog because
    # it is not needed in every app and package
    "@react-native/assets-registry": ~0.76.2
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
    react: 18.3.1
    react-dom: 18.3.1
    react-native: ^0.77.0
