/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "AuthChallengeEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthHomefrontClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthHomefrontClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthMiniSessionEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthSalt": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthSessionCreatorSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DbEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OauthEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OauthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OtpEncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PineconeApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Redis": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "StripeHashKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Vpc": {
      "type": "sst.aws.Vpc"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "homefront-next-prod": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "join-homefront": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
